### ISSUE TITLE
Cannot find module '../dist/cli'

### ISSUE THREAD

**Issue by awatson1978** [mantrajs/mantra-cli#13]
A new user who doesn't know anything about Mantra gets the following error when running `mantra create foo` for the first time:

``` sh
Error: Cannot find module '../dist/cli'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/mantra-cli/bin/mantra:3:1)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:475:10)
Abigails-Mac-mini:Mantra abigailwatson$ mantra generate foo
module.js:338
    throw err;
```

**Comment by sungwoncho** [comment]
Can you provide versions of OS, node, and mantra-cli you are using? Also, did `npm install` give you any error?

**Comment by sungwoncho** [comment]
@awatson1978 Can you provide more details?

**Comment by awatson1978** [comment]
Sorry, caught up with lots of work.  Using Mac OS, node `v4.1.0`, and presumably the latest version of mantra-cli.  `npm install` gave no errors, as I recall.

**Comment by sungwoncho** [comment]
Can you upgrade to the latest version [v0.3.5](https://github.com/mantrajs/mantra-cli/blob/master/RELEASE_NOTE.md#035-march-15-2016) and check if this problem persists?

**Comment by awatson1978** [comment]
Unfortunately, not.  We're still on `Meteor@1.1.0.3` until this summer, because of our QA program.  Looks like we're going to need to skip Matra CLI for the time being.  Good luck.
