### ISSUE TITLE
problems with module creation (fs module failed somewhat)

### ISSUE THREAD

**Issue by roberto68** [mantrajs/mantra-cli#26]
Os I tried to create a module named gallery but this is the output.
`$ mantra g module gallery
  create  client/modules/gallery/
  create  client/modules/gallery/components/
  create  client/modules/gallery/containers/
  create  client/modules/gallery/configs/
  create  client/modules/gallery/actions/index.js
  create  client/modules/gallery/index.js
  create  client/modules/gallery/routes.jsx
fs.js:585
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open './client/main.js'
    at Error (native)
    at Object.fs.openSync (fs.js:585:18)
    at Object.fs.readFileSync (fs.js:432:33)
    at editFile (/home/roberto/.nvm/versions/node/v5.2.0/lib/node_modules/mantra-cli/dist/utils.js:42:34)
    at insertToFile (/home/roberto/.nvm/versions/node/v5.2.0/lib/node_modules/mantra-cli/dist/utils.js:63:3)
    at generateModule (/home/roberto/.nvm/versions/node/v5.2.0/lib/node_modules/mantra-cli/dist/generators/module.js:37:27)
    at generate (/home/roberto/.nvm/versions/node/v5.2.0/lib/node_modules/mantra-cli/dist/commands/generate.js:75:3)
    at Command.<anonymous> (/home/roberto/.nvm/versions/node/v5.2.0/lib/node_modules/mantra-cli/dist/cli.js:22:26)
    at Command.listener (/home/roberto/.nvm/versions/node/v5.2.0/lib/node_modules/mantra-cli/node_modules/commander/index.js:301:8)
    at emitTwo (events.js:88:13)
`   It looks like it is smth with fs module but what it is... all I can recall that node sometimes complains on some optional dependency on fs (cause it's designed for OSX) and I'm on linux, but I've no clue if this can be related to this issue or not.

**Comment by sungwoncho** [comment]
I think the reason is either that:
1. You are not in the app root directory (see [here](https://github.com/mantrajs/mantra-cli#documentation))
2. There is no `./client/main.js`

If so, it is not a bug from CLI. However, if you think it is a bug, please provide your node version and CLI version.

**Comment by macrozone** [comment]
@roberto68  is this still an issue? reopen if so!
