### ISSUE TITLE
File not found with mantra create myapp

### ISSUE THREAD

**Issue by mmoyles87** [mantrajs/mantra-cli#6]
Using nodejs 5.4.1 on OSX

```
  run  meteor create databook --release 1.3-beta.11
  create  databook/
  create  databook/client/configs/context.js
  create  databook/client/main.js
  create  databook/client/modules/core/index.js
  create  databook/client/modules/core/routes.jsx
  create  databook/client/modules/core/containers/
  create  databook/client/modules/core/configs/
  create  databook/client/modules/core/actions/index.js
  create  databook/client/modules/core/components/main_layout.jsx
  create  databook/client/modules/core/components/home.jsx
fs.js:584
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open '/Users/matt/.nvm/versions/node/v5.4.1/lib/node_modules/mantra-cli/dist/commands/../../templates/lib/collections/index.js'
    at Error (native)
    at Object.fs.openSync (fs.js:584:18)
    at Object.fs.readFileSync (fs.js:431:33)
    at getFileContent (/Users/matt/.nvm/versions/node/v5.4.1/lib/node_modules/mantra-cli/dist/commands/create.js:32:45)
    at createFile (/Users/matt/.nvm/versions/node/v5.4.1/lib/node_modules/mantra-cli/dist/commands/create.js:42:28)
    at create (/Users/matt/.nvm/versions/node/v5.4.1/lib/node_modules/mantra-cli/dist/commands/create.js:79:10)
    at Command.<anonymous> (/Users/matt/.nvm/versions/node/v5.4.1/lib/node_modules/mantra-cli/dist/cli.js:18:24)
    at Command.listener (/Users/matt/.nvm/versions/node/v5.4.1/lib/node_modules/mantra-cli/node_modules/commander/index.js:301:8)
    at emitTwo (events.js:87:13)
    at Command.emit (events.js:172:7)
```

**Comment by sungwoncho** [comment]
npm was ignoring a template directory. Fixed on 0.2.1.
