### ISSUE TITLE
component generation bug on 3.10

### ISSUE THREAD

**Issue by sakulstra** [mantrajs/mantra-cli#62]
Hello,
when trying to generate a component `mantra g component microphone:core` I get:

```
create ./client/modules/microphone/components/core.jsx
fs.js:549
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open './client/modules/microphone/components/tests/core.js'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.fs.writeFileSync (fs.js:1156:15)
    at _generateTest (/usr/lib/node_modules/mantra-cli/dist/generators/utils.js:362:16)
    at generateComponent (/usr/lib/node_modules/mantra-cli/dist/generators/component.js:27:28)
    at generate (/usr/lib/node_modules/mantra-cli/dist/commands/generate.js:75:3)
    at Command.<anonymous> (/usr/lib/node_modules/mantra-cli/dist/cli.js:22:26)
    at Command.listener (/usr/lib/node_modules/mantra-cli/node_modules/commander/index.js:301:8)
    at emitTwo (events.js:87:13)
    at Command.emit (events.js:172:7)
```

Regards,
Lukas

**Comment by sungwoncho** [comment]
Happened because apps generated with previous version of CLI does not have tests directories. Fixed in [0.3.11](https://github.com/mantrajs/mantra-cli/blob/master/RELEASE_NOTE.md#0311-april-24-2016). 👍
